version: "3.9"

services:
  web:
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py test
      "
    environment:
      DJANGO_SETTINGS_MODULE: stockq.settings.local
    depends_on:
      - db
      - redis

  celery_worker:
    command: >
      sh -c "
        python manage.py migrate &&
        celery -A stockq worker -l info
      "
    environment:
      DJANGO_SETTINGS_MODULE: stockq.settings.local
    depends_on:
      - db
      - redis

  celery_beat:
    command: >
      sh -c "
        python manage.py migrate &&
        celery -A stockq beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    environment:
      DJANGO_SETTINGS_MODULE: stockq.settings.local
    depends_on:
      - db
      - redis
