# Generated by Django 5.2.1 on 2025-08-19 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_news_price_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='stock',
        ),
        migrations.AddField(
            model_name='news',
            name='canonical_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(blank=True, default='Stock', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('stock', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='favoritestock',
            index=models.Index(fields=['user', 'stock'], name='stocks_favo_user_id_2b976c_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['stock', '-timestamp'], name='stocks_pric_stock_i_d8a691_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['stock', '-date'], name='stocks_summ_stock_i_2b8091_idx'),
        ),
        migrations.AddField(
            model_name='newsstock',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.news'),
        ),
        migrations.AddField(
            model_name='newsstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='news',
            name='stocks',
            field=models.ManyToManyField(related_name='news', through='stocks.NewsStock', to='stocks.stock'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at'], name='stocks_news_publish_6a1c08_idx'),
        ),
        migrations.AddIndex(
            model_name='newsstock',
            index=models.Index(fields=['stock', 'news'], name='stocks_news_stock_i_437f69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsstock',
            unique_together={('news', 'stock')},
        ),
    ]
