# Generated by Django 5.2.1 on 2025-08-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_populate_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
