# Generated by Django 5.2.3 on 2025-09-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='favoritestock',
            name='stocks_favo_user_id_2b976c_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='stocks_news_publish_6a1c08_idx',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='stocks_pric_stock_i_d8a691_idx',
        ),
        migrations.AlterField(
            model_name='news',
            name='url_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
