# Generated by Django 5.2.3 on 2025-09-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_remove_favoritestock_stocks_favo_user_id_2b976c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyusernews',
            name='stocks_dail_user_id_6ced67_idx',
        ),
        migrations.RemoveIndex(
            model_name='summary',
            name='stocks_summ_stock_i_2b8091_idx',
        ),
    ]
