# Generated by Django 5.2.3 on 2025-09-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_remove_dailyusernews_stocks_dail_user_id_6ced67_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
