# Generated by Django 5.2.3 on 2025-09-18 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_news_url_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritestock',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='favoritestock',
            index=models.Index(fields=['user', 'stock'], name='stocks_favo_user_id_2b976c_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoritestock',
            constraint=models.UniqueConstraint(fields=('user', 'stock'), name='uq_user_stock'),
        ),
    ]
