# Generated by Django 5.2.3 on 2025-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_favoritestock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
