# Generated by Django 5.2.3 on 2026-03-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_news_external_id_alter_news_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.JSONField(),
        ),
    ]
