# Generated by Django 5.2.3 on 2026-03-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_alter_summary_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('before_input_tokens', models.PositiveIntegerField(default=0)),
                ('after_input_tokens', models.PositiveIntegerField(default=0)),
                ('raw_count', models.PositiveIntegerField(default=0)),
                ('relevant_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('no_news', 'No News'), ('no_relevant_news', 'No Relevant News'), ('failed', 'Failed')], max_length=30)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_generation_logs', to='stocks.stock')),
            ],
            options={
                'db_table': 'summary_generation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', 'date'], name='summary_gen_stock_i_c7a92c_idx'), models.Index(fields=['status'], name='summary_gen_status_7c7334_idx'), models.Index(fields=['created_at'], name='summary_gen_created_993ee8_idx')],
            },
        ),
    ]
