# Generated by Django 5.2.3 on 2026-03-28 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_summarygenerationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retry_wait', 'Retry Wait')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_jobs', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'date'], name='stocks_summ_status_2e25c3_idx'), models.Index(fields=['stock', 'date'], name='stocks_summ_stock_i_53e6ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='uniq_summary_job_stock_date')],
            },
        ),
    ]
