# Generated by Django 5.2.3 on 2026-03-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_summaryjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryjob',
            old_name='last_error',
            new_name='error_message',
        ),
        migrations.AddField(
            model_name='summaryjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summaryjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summaryjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retry_wait', 'Retry Wait'), ('no_news', 'No News'), ('no_relevant_news', 'No Relevant News')], default='pending', max_length=20),
        ),
    ]
