# Generated by Django 5.2.3 on 2026-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_rename_last_error_summaryjob_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='summaryjob',
            name='stocks_summ_stock_i_53e6ac_idx',
        ),
        migrations.AddField(
            model_name='summaryjob',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summaryjob',
            name='lease_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='summaryjob',
            name='retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='summaryjob',
            index=models.Index(fields=['status', 'retry_at'], name='stocks_summ_status_e99040_idx'),
        ),
        migrations.AddIndex(
            model_name='summaryjob',
            index=models.Index(fields=['status', 'dispatched_at'], name='stocks_summ_status_4f4746_idx'),
        ),
        migrations.AddIndex(
            model_name='summaryjob',
            index=models.Index(fields=['status', 'started_at'], name='stocks_summ_status_349a02_idx'),
        ),
    ]
