# Generated by Django 5.2.3 on 2026-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_remove_summaryjob_stocks_summ_stock_i_53e6ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='profile_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='web_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
