name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: stockq
          POSTGRES_USER: stockq
          POSTGRES_PASSWORD: stockq123
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U stockq"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - "6379:6379"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://stockq:stockq123@localhost:5432/stockq
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
