name: Django CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create .env file for CI
        run: |
          echo "FINNHUB_API_KEY=dummy-finnhub-key" >> .env
          echo "OPENAI_API_KEY=dummy-openai-key" >> .env
          echo "SECRET_KEY=dummy-secret-key" >> .env

      - name: Run CI with Docker Compose
        run: docker compose -f docker-compose.dev.yml -f docker-compose.ci.yml up --build --exit-code-from web

      - name: Show logs
        if: always()
        run: docker compose -f docker-compose.dev.yml -f docker-compose.ci.yml logs

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.dev.yml -f docker-compose.ci.yml down -v