name: Django CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create .env file from secrets
        run: |
          echo "FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      # ✅ dev + ci 함께 실행 (한 번만)
      - name: Run CI with Docker Compose
        run: docker compose -f docker-compose.dev.yml -f docker-compose.ci.yml up --build --abort-on-container-exit

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.dev.yml -f docker-compose.ci.yml down
