name: Django CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run tests with Docker Compose
        run: docker compose -f docker-compose.ci.yml up --build --abort-on-container-exit --exit-code-from web

      - name: Show logs
        if: always()
        run: docker compose -f docker-compose.ci.yml logs

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.ci.yml down -v
